modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="broken_not_shattered.png"
authors="${mod_authors}"
description='''
Damageable items reach zero durability and become temporarily unusable instead of disappearing. Repairing any durability makes the original stack work again.
'''

[[mixins]]
config="broken_not_shattered.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
